# Documentation à propos de cette page : https://fshschool.org/docs/sushi/configuration/

id: ans.hl7v2.fr.transmission-cda-r2
canonical: https://interop.esante.gouv.fr/ig/hl7v2/transmission-cda-r2 # the last part of canonical and id must be the same
name: Hl7v2_CDAr2 # Should be an acronym
title: ANS IG du volet de transmission d'un document CDA-R2 en HL7v2
publisher:
  name: Agence du Numérique en Santé (ANS) - 2-10 Rue d'Oradour-sur-Glane, 75015 Paris
  url: https://esante.gouv.fr
status: draft
version: 2.1.0 # shall conforms to Semantic Versioning https://fr.wiktionary.org/wiki/SemVer
fhirVersion: 4.0.1
copyrightYear: 2020+
releaseLabel: ci-build
jurisdiction: urn:iso:std:iso:3166#FR "FRANCE"

parameters:
    shownav: 'true'

pages:
    index.md:
        title: "Accueil"
    cas-usage.md:
        title: "Cas d'usage"
    contexte-metier.md:
        title: "Organisation du contexte métier"
    acteurs-transactions.md:
        title: "Acteurs et transactions"
    def-proc-collab.md:
        title: "Définition des processus collaboratifs"
    identification-flux.md:
        title: "identification des flux"
    perimetre-transaction.md:
        title: "Périmètre de la transaction"
    role.md:
        title: "Rôle des acteurs pour cette transaction"
    standards.md:
        title: "Choix des standards"
    evenements-declenchants.md:
        title: "Evènements déclenchants"
    interactions-acteurs.md:
        title: "Interactions entre les Acteurs"
    profils-messages.md:
        title: "Profils de messages"
    regles-gestion-mssante.md:
        title: "Règles de gestion MSSANTE"
    testplan.md:
        title: "Test Plan"
    issues.md:
        title: "Issues"
    error-codes.md:
        title: "Error codes"
    additional.md:
        title: "Error codes"
    change-log.md:
        title: "Change log"
    download.md:
        title: "Téléchargements et usages"
        generation: markdown

menu:
    Accueil: index.html
    Volume 1 - Etude fonctionnelle: 
        "Cas d'usage": cas-usage.html
        "Organisation du contexte métier": contexte-metier.html
        "Acteurs et transactions": acteurs-transactions.html
        "Définition des processus collaboratifs": def-proc-collab.html
        "identification des flux": identification-flux.html
    Volume 2 – Détail des Transactions:
        "Périmètre de la transaction": perimetre-transaction.html
        "Rôle des acteurs pour cette transaction": role.html
        "Choix des standards": standards.html
        "Evènements déclenchants": evenements-declenchants.html
        "Interactions entre les Acteurs": interactions-acteurs.html
        "Profils de messages": profils-messages.html
        "Règles de gestion MSSANTE": regles-gestion-mssante.html
    Volume 3:
        "Error Codes": error-codes.html
        "Compléments": additional.html
    Test Plan: testplan.html
    Change log: change-log.html
    Téléchargements et usage: download.html
    Documentation: new-tab https://interop.esante.gouv.fr/ig/documentation/