# Documentation à propos de cette page : https://fshschool.org/docs/sushi/configuration/

id: ans.hl7v2.fr.trans-cda-r2
canonical: https://interop.esante.gouv.fr/ig/hl7v2/trans-cda-r2 # the last part of canonical and id must be the same
name: CISIS_CDA_HL7_V2 # Should be an acronym
title: Volet de transmission d'un document CDA-R2 en HL7v2
publisher:
  name: Agence du Numérique en Santé (ANS) - 2-10 Rue d'Oradour-sur-Glane, 75015 Paris
  url: https://esante.gouv.fr
status: draft
version: 2.1.1 # shall conforms to Semantic Versioning https://fr.wiktionary.org/wiki/SemVer
fhirVersion: 4.0.1
copyrightYear: 2020+
releaseLabel: ci-build
jurisdiction: urn:iso:std:iso:3166#FR "FRANCE"

parameters:
    shownav: 'true'

pages:
    index.md:
        title: "Accueil"
    volume1.md:
        title: "Volume 1 : Etude fonctionnelle"
    volume2.md:
        title: "Volume 2 : Détail des transactions"        
    cas-usage.md:
        title: "Cas d'usage"
    contexte-metier.md:
        title: "Organisation du contexte métier"
    acteurs-transactions.md:
        title: "Acteurs et transactions"
    def-proc-collab.md:
        title: "Définition des processus collaboratifs"
    identification-flux.md:
        title: "identification des flux"
    perimetre-transaction.md:
        title: "Périmètre de la transaction"
    role.md:
        title: "Rôle des acteurs pour cette transaction"
    standards.md:
        title: "Choix des standards"
    evenements-declenchants.md:
        title: "Evènements déclenchants"
    interactions-acteurs.md:
        title: "Interactions entre les Acteurs"
    profils-messages.md:
        title: "Profils de messages"
    regles-gestion-mssante.md:
        title: "Règles de gestion MSSANTE"
    meta-dmp-mss.md:
        title: "Table MetaDMP/MSS"
    ack-metier-zam.md:
        title: "Table AckMetierZAM"
    exemples.md:
        title: "Exemples de messages"
    struct-msg-mdn.md:
        title: "Structure du MDN (MSSanté)"
    error-codes.md:
        title: "Error codes"
    glossaire.md:
        title: "Glossaire"
    doc-ref.md:
        title: "Documents de référence"
    testplan.md:
        title: "Test"
    change-log.md:
        title: "Historique des versions"
    download.md:
        title: "Téléchargements"
        generation: markdown
    mapping.md:
        title: "Mapping"      
menu:
    Accueil: index.html
    Volume 1 - Etude fonctionnelle: 
        "Cas d'usage": volume1.html#cas-dusage
        "Organisation du contexte métier": volume1.html#organisation-du-contexte-métier
        "Acteurs et transactions": volume1.html#acteurs-et-transactions
        "Définition des processus collaboratifs": volume1.html#définition-des-processus-collaboratifs
        "identification des flux": volume1.html#identification-des-flux
    Volume 2 – Détail des Transactions: 
        "Introduction": volume2.html#introduction
        "Périmètre de la transaction": volume2.html#périmetre-de-la-transaction
        "Rôle des acteurs pour cette transaction": volume2.html#rôle-des-acteurs-pour-cette-transaction
        "Choix des standards": volume2.html#choix-des-standards
        "Evènements déclenchants": volume2.html#evènements-déclenchants
        "Interactions entre les Acteurs": volume2.html#interactions-entre-les-acteurs
        "Profils de messages": volume2.html#profils-de-messages
        "Règles de gestion MSSANTE": volume2.html#règles-de-gestion-mssante
    Volume 3 - Annexes:
        "Table MetaDMP/MSS": meta-dmp-mss.html
        "Structure du MDN (MSSanté)": struct-msg-mdn.html
        "Table AckMetierZAM": ack-metier-zam.html
        "Mapping": mapping.html
        "Exemples de messages": exemples.html
        "Error Codes": error-codes.html
        "Glossaire": glossaire.html
        "Documents de référence": doc-ref.html
    Test: testplan.html
    Historique des versions: change-log.html
    Téléchargements: download.html
 #   Documentation: new-tab https://interop.esante.gouv.fr/ig/documentation/
