name: "Change Proposal template"
description: "[CI-SIS]Change Proposal pour le volet de transmission d’un document CDA-R2 en HL7v2."
title: "[CP]: "
labels: ["CP"]

body:
  - type: markdown
    id: volet
    attributes:
      value: "### [CI-SIS]Volet de transmission d’un document CDA-R2 en HL7v2"
  - type: input
    id: section_identification
    attributes:
      label: "Identification de la section à changer"
      description: "Identifier la section du volet concernée par la demande de changement (numéro de la section exemple 12.2.2, ou directement le lien lorsque le volet est sous forme de guide d'implémentation)"
      placeholder: "Entrez le numéro ou le lien de la section"
    validations:
      required: true

  - type: textarea
    id: issue_description
    attributes:
      label: "Votre demande de changement"
      description: "Description de votre demande, du contexte, du problème rencontré"
      placeholder: "Décrivez votre demande"
    validations:
      required: true

  - type: textarea
    id: proposed_change
    attributes:
      label: "Votre proposition de changement"
      description: "Proposer une modification (par exemple, une nouvelle formulation suggérée ou la description d'un moyen de résoudre le problème).\nProposer une solution ou une modification est fortement recommandé.\n Pour une suppression vous pouvez reprendre le texte et le barrer. \n Pour un ajout vous pouvez reprendre le paragraphe ou la section et surligner le texte ajouté.\n Vous pouvez également proposer une Pull Request (PR) lorsque le volet est sur un repository github et placer le lien ici vers cette PR"
      placeholder: "Proposez votre modification"
    validations:
      required: true

  - type: textarea
    id: impact_assessment
    attributes:
      label: "Votre évaluation d'impact du changement "
      description: "Veuillez indiquer ci-dessous votre évaluation de(s) impact(s) (gains et/ou risques) du changement proposé"
    validations:
      required: false
  
  - type: textarea
    id: complement
    attributes:
      label: Eléments complémentaires
      description: |
        Liens? References? Tout ce qui peut nous aider à mieux comprendre le problème que vous rencontrez

        Tip: Vous pouvez joindre des images ou des fichiers en cliquant sur cette zone pour la mettre en surbrillance, puis en y faisant glisser les fichiers.
    validations:
      required: false
