name: "Change Proposal template"
description: "Change Proposal pour un volet du CI-SIS"
title: "[CP]: "
labels: ["CP", "backlog"]

body:
  - type: input
    id: contact
    attributes:
      label: Contact
      description: Comment vous contacter si nous avons besoin de plus d'information?
      placeholder: ex. email@example.com
    validations:
      required: false
  - type: input
    id: section_identification
    attributes:
      label: "Identification de la section à changer"
      description: "Identifier la section du volet concernée par la demande de changement (numéro de la section exemple 12.2.2, ou directement le lien lorsque le volet est sous forme de guide d'implémentation)"
      placeholder: "Entrez le numéro ou le lien de la section"
    validations:
      required: true

  - type: textarea
    id: issue_description
    attributes:
      label: "Votre issue"
      description: "Description de votre demande"
      placeholder: "Décrivez votre demande"
    validations:
      required: true

  - type: textarea
    id: proposed_change
    attributes:
      label: "Votre proposition de changement"
      description: "Proposer une solution (par exemple, une nouvelle formulation suggérée ou la description d'un moyen de résoudre le problème). Proposer une solution ou une modification est fortement recommandé. Pour une suppression vous pouvez reprendre le texte et le barrer. Pour un ajout vous pouvez reprendre le paragraphe ou la section et surligner le texte ajouté"
      placeholder: "Proposez votre solution"
    validations:
      required: false

  - type: dropdown
    id: impact_assessment
    attributes:
      label: "Votre évaluation d'impact"
      multiple: false
      description: |
        - **Majeur**: Question importante où il y a un problème majeur à résoudre. Nécessitera une concertation
        - **Mineur**: Par exemple typo ou reformulation ne nécessitant pas de mise en concertation
      options:
        - Majeur
        - Mineur
    validations:
      required: true
  
  - type: textarea
    attributes:
      label: 2léments complémentaires
      description: |
        Liens? References? Tout ce qui peut nous aider à mieux comprendre le problème que vous rencontrez

        Tip: Vous pouvez joindre des images ou des fichiers en cliquant sur cette zone pour la mettre en surbrillance, puis en y faisant glisser les fichiers.
    validations:
      required: false
